import { serve } from 'https://deno.land/std@0.168.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.81.0';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { bookId, pages, pageCount, podPackageId } = await req.json();

    if (!bookId || !pages || !Array.isArray(pages)) {
      return new Response(
        JSON.stringify({ error: 'Missing required parameters: bookId, pages' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    console.log(`[generate-interior-pdf] Generating interior PDF for book ${bookId}`);
    console.log(`  Pages: ${pages.length}, Target count: ${pageCount}`);

    // Create Supabase client with service role for RLS bypass
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    // For now, we'll use the client-side repairBookPdf function
    // This is a placeholder that returns success - the actual PDF generation
    // happens in the client after the book is saved
    // TODO: Move PDF generation fully to edge function in future

    return new Response(
      JSON.stringify({ 
        success: true,
        message: 'PDF generation queued - will be processed by client',
        pdfUrl: null // Will be generated by client
      }),
      { 
        status: 200, 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
      }
    );
  } catch (error: any) {
    console.error('[generate-interior-pdf] Error:', error);
    return new Response(
      JSON.stringify({ error: error.message }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
